services:
  backend:
    build:
      context: ../..
      dockerfile: docker/backend/Dockerfile.ultra-lite
    container_name: ProcStudio-PDF-Ultra-Lite
    restart: on-failure:5
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP'"]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - "8080:8080"
    volumes:
      - ../../procstudio/latest/config:/configs:rw
      - ../../procstudio/latest/logs:/logs:rw
    environment:
      DISABLE_ADDITIONAL_FEATURES: "true"
      SECURITY_ENABLELOGIN: "false"
      ENDPOINTS_GROUPS_TO_REMOVE: "CLI"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: ProcStudio PDF Ultra-lite
      UI_HOMEDESCRIPTION: Demo site for ProcStudio PDF Ultra-lite
      UI_APPNAMENAVBAR: ProcStudio PDF Ultra-lite
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
      SHOW_SURVEY: "true"
    networks:
      - procstudio-network

  frontend:
    build:
      context: ../..
      dockerfile: docker/frontend/Dockerfile
    container_name: procstudio-pdf-frontend-ultra-lite
    restart: on-failure:5
    ports:
      - "3000:80"
    environment:
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - procstudio-network

networks:
  procstudio-network:
    driver: bridge

volumes:
  procstudio-data:
  procstudio-config:
  procstudio-logs:
